import {
  DEX_PRECOMPILE_ABI,
  ERC20_ABI,
  ERC20_PRECOMPILE_ABI,
  ERC721_ABI,
  ERC721_PRECOMPILE_ABI,
  ERC1155_ABI,
  ERC1155_PRECOMPILE_ABI,
  FEE_PROXY_ABI,
  FEE_PROXY_PRECOMPILE_ABI,
  FUTUREPASS_PRECOMPILE_ABI,
  FUTUREPASS_REGISTRAR_PRECOMPILE_ABI,
  NFT_PRECOMPILE_ABI,
  SFT_PRECOMPILE_ABI,
} from '@therootnetwork/evm';
import { parseAbi } from 'viem';

import ERC20_ORIGINAL from './erc20.json';
import ERC165_ORIGINAL from './erc165.json';
import ERC721_ORIGINAL from './erc721.json';
import ERC721A_ORIGINAL from './erc721a.json';
import ERC1155_ORIGINAL from './erc1155.json';
import UNISWAPV2_FACTORY from './uniswapv2-factory.json';
import UNISWAPV2_ROUTER from './uniswapv2-router.json';

/** @dev - List is exported basedon PRIORITY */
export default {
  ERC20_ORIGINAL,
  ERC20_ABI: parseAbi(ERC20_ABI),
  ERC20_PRECOMPILE_ABI: parseAbi(ERC20_PRECOMPILE_ABI),
  ERC721_ORIGINAL,
  ERC721_ABI: parseAbi(ERC721_ABI),
  ERC721_PRECOMPILE_ABI: parseAbi(ERC721_PRECOMPILE_ABI),
  ERC721A_ORIGINAL: ERC721A_ORIGINAL,
  ERC1155_ORIGINAL,
  ERC1155_ABI: parseAbi(ERC1155_ABI),
  ERC1155_PRECOMPILE_ABI: parseAbi(ERC1155_PRECOMPILE_ABI),
  FUTUREPASS_REGISTRAR_PRECOMPILE_ABI: parseAbi(FUTUREPASS_REGISTRAR_PRECOMPILE_ABI),
  FUTUREPASS_PRECOMPILE_ABI: parseAbi(FUTUREPASS_PRECOMPILE_ABI),
  ERC165_ORIGINAL,
  UNISWAPV2_ROUTER,
  DEX_PRECOMPILE_ABI: parseAbi(DEX_PRECOMPILE_ABI),
  NFT_PRECOMPILE_ABI: parseAbi(NFT_PRECOMPILE_ABI),
  SFT_PRECOMPILE_ABI: parseAbi(SFT_PRECOMPILE_ABI),
  FEE_PROXY_ABI: parseAbi(FEE_PROXY_ABI),
  FEE_PROXY_PRECOMPILE_ABI: parseAbi(FEE_PROXY_PRECOMPILE_ABI),
  UNISWAPV2_FACTORY,
};
