const { fontFamily } = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      backgroundImage: {
        'main-image': "url('/bg.jpg')",
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        local: ['var(--font-local)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  safelist: [
    'w-[1%]',
    'w-[2%]',
    'w-[3%]',
    'w-[4%]',
    'w-[5%]',
    'w-[6%]',
    'w-[7%]',
    'w-[8%]',
    'w-[9%]',
    'w-[10%]',
    'w-[11%]',
    'w-[12%]',
    'w-[13%]',
    'w-[14%]',
    'w-[15%]',
    'w-[16%]',
    'w-[17%]',
    'w-[18%]',
    'w-[19%]',
    'w-[20%]',
    'w-[21%]',
    'w-[22%]',
    'w-[23%]',
    'w-[24%]',
    'w-[25%]',
    'w-[26%]',
    'w-[27%]',
    'w-[28%]',
    'w-[29%]',
    'w-[30%]',
    'w-[31%]',
    'w-[32%]',
    'w-[33%]',
    'w-[34%]',
    'w-[35%]',
    'w-[36%]',
    'w-[37%]',
    'w-[38%]',
    'w-[39%]',
    'w-[40%]',
    'w-[41%]',
    'w-[42%]',
    'w-[43%]',
    'w-[44%]',
    'w-[45%]',
    'w-[46%]',
    'w-[47%]',
    'w-[48%]',
    'w-[49%]',
    'w-[50%]',
    'w-[51%]',
    'w-[52%]',
    'w-[53%]',
    'w-[54%]',
    'w-[55%]',
    'w-[56%]',
    'w-[57%]',
    'w-[58%]',
    'w-[59%]',
    'w-[60%]',
    'w-[61%]',
    'w-[62%]',
    'w-[63%]',
    'w-[64%]',
    'w-[65%]',
    'w-[66%]',
    'w-[67%]',
    'w-[68%]',
    'w-[69%]',
    'w-[70%]',
    'w-[71%]',
    'w-[72%]',
    'w-[73%]',
    'w-[74%]',
    'w-[75%]',
    'w-[76%]',
    'w-[77%]',
    'w-[78%]',
    'w-[79%]',
    'w-[80%]',
    'w-[81%]',
    'w-[82%]',
    'w-[83%]',
    'w-[84%]',
    'w-[85%]',
    'w-[86%]',
    'w-[87%]',
    'w-[88%]',
    'w-[89%]',
    'w-[90%]',
    'w-[91%]',
    'w-[92%]',
    'w-[93%]',
    'w-[94%]',
    'w-[95%]',
    'w-[96%]',
    'w-[97%]',
    'w-[98%]',
    'w-[99%]',
    'w-[100%]',
  ],
  plugins: [require('tailwindcss-animate')],
};
