/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      backgroundImage: {
        'main-image': "url('/bg.jpg')",
        'api-portal-banner':
          'linear-gradient(90deg, rgba(143, 154, 233, 0.10) 0%, rgba(224, 188, 149, 0.10) 50%, rgba(247, 143, 80, 0.10) 100%)',
        'footer-pattern-desktop': "url('/footer-pattern-desktop.png')",
        'footer-pattern-tablet': "url('/footer-pattern-tablet.png')",
        'footer-pattern-mobile': "url('/footer-pattern-mobile.png')",
        'home-page-hero-section-desktop': "url('/home-page-hero-section-desktop.png')",
        'home-page-hero-section-tablet': "url('/home-page-hero-section-tablet.png')",
        'home-page-hero-section-mobile': "url('/home-page-hero-section-mobile.png')",
      },
      colors: {
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },

        // COLOR PRIMITIVES
        white: 'rgb(var(--white))',
        black: 'rgb(var(--black))',
        grey: {
          900: 'rgb(var(--grey-900))',
          800: 'rgb(var(--grey-800))',
          700: 'rgb(var(--grey-700))',
          600: 'rgb(var(--grey-600))',
          500: 'rgb(var(--grey-500))',
          400: 'rgb(var(--grey-400))',
          300: 'rgb(var(--grey-300))',
          200: 'rgb(var(--grey-200))',
          100: 'rgb(var(--grey-100))',
        },
        green: {
          900: 'rgb(var(--green-900))',
          700: 'rgb(var(--green-700))',
          500: 'rgb(var(--green-500))',
          100: 'rgb(var(--green-100))',
        },
        blue: {
          900: 'rgb(var(--blue-900))',
          700: 'rgb(var(--blue-700))',
          500: 'rgb(var(--blue-500))',
          100: 'rgb(var(--blue-100))',
        },
        orange: {
          900: 'rgb(var(--orange-900))',
          700: 'rgb(var(--orange-700))',
          500: 'rgb(var(--orange-500))',
          100: 'rgb(var(--orange-100))',
        },
        red: {
          500: 'rgb(var(--red-500))',
          300: 'rgb(var(--red-300))',
          100: 'rgb(var(--red-100))',
        },
        text: {
          foreground: 'rgb(var(--text-foreground))',
          secondary: 'rgb(var(--text-secondary))',
          placeholder: 'rgb(var(--text-placeholder))',
          info: 'rgb(var(--text-info))',
          'info-primary': 'rgb(var(--text-info-primary))',
          success: 'rgb(var(--text-success))',
          'success-primary': 'rgb(var(--text-success-primary))',
          warning: 'rgb(var(--text-warning))',
          'warning-primary': 'rgb(var(--text-warning-primary))',
          error: 'rgb(var(--text-error))',
          disabled: 'rgb(var(--text-disabled))',
          light: 'rgb(var(--text-light))',
        },
        surface: {
          container: 'rgb(var(--surface-container))',
          bg: 'rgb(var(--surface-bg))',
          card: 'rgb(var(--surface-card))',
          info: 'rgb(var(--surface-info))',
          success: 'rgb(var(--surface-success))',
          warning: 'rgb(var(--surface-warning))',
          error: 'rgb(var(--surface-error))',
          'error-primary': 'rgb(var(--surface-error-primary))',
          'error-hover': 'rgb(var(--surface-error-hover))',
          primary: 'rgb(var(--surface-primary))',
          hover: 'rgb(var(--surface-hover))',
          'hover-secondary': 'rgb(var(--surface-hover-secondary))',
          alert: 'rgb(var(--surface-alert))',
          disabled: 'rgb(var(--surface-disabled))',
          fill: 'rgb(var(--surface-fill))',
          'fill-secondary': 'rgb(var(--surface-fill-secondary))',
          button2: 'rgb(var(--surface-button2))',
        },
        border: {
          DEFAULT: 'hsl(var(--border))', // LEGACY
          primary: 'rgb(var(--border-primary))',
          secondary: 'rgb(var(--border-secondary))',
          tertiary: 'rgb(var(--border-tertiary))',
          active: 'rgb(var(--border-active))',
          error: 'rgb(var(--border-error))',
          info: 'rgb(var(--border-info))',
          success: 'rgb(var(--border-success))',
          warning: 'rgb(var(--border-warning))',
        },
        tag: {
          'blue-light': 'rgb(var(--tag-blue-light))',
          'blue-dark': 'rgb(var(--tag-blue-dark))',
          'green-light': 'rgb(var(--tag-green-light))',
          'green-dark': 'rgb(var(--tag-green-dark))',
          'orange-light': 'rgb(var(--tag-orange-light))',
          'orange-dark': 'rgb(var(--tag-orange-dark))',
        },
        code: {
          yellow: 'rgb(var(--code-yellow))',
          cyan: 'rgb(var(--code-cyan))',
          green: 'rgb(var(--code-green))',
          red: 'rgb(var(--code-red))',
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        local: ['var(--font-local)'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  safelist: [
    'w-[1%]',
    'w-[2%]',
    'w-[3%]',
    'w-[4%]',
    'w-[5%]',
    'w-[6%]',
    'w-[7%]',
    'w-[8%]',
    'w-[9%]',
    'w-[10%]',
    'w-[11%]',
    'w-[12%]',
    'w-[13%]',
    'w-[14%]',
    'w-[15%]',
    'w-[16%]',
    'w-[17%]',
    'w-[18%]',
    'w-[19%]',
    'w-[20%]',
    'w-[21%]',
    'w-[22%]',
    'w-[23%]',
    'w-[24%]',
    'w-[25%]',
    'w-[26%]',
    'w-[27%]',
    'w-[28%]',
    'w-[29%]',
    'w-[30%]',
    'w-[31%]',
    'w-[32%]',
    'w-[33%]',
    'w-[34%]',
    'w-[35%]',
    'w-[36%]',
    'w-[37%]',
    'w-[38%]',
    'w-[39%]',
    'w-[40%]',
    'w-[41%]',
    'w-[42%]',
    'w-[43%]',
    'w-[44%]',
    'w-[45%]',
    'w-[46%]',
    'w-[47%]',
    'w-[48%]',
    'w-[49%]',
    'w-[50%]',
    'w-[51%]',
    'w-[52%]',
    'w-[53%]',
    'w-[54%]',
    'w-[55%]',
    'w-[56%]',
    'w-[57%]',
    'w-[58%]',
    'w-[59%]',
    'w-[60%]',
    'w-[61%]',
    'w-[62%]',
    'w-[63%]',
    'w-[64%]',
    'w-[65%]',
    'w-[66%]',
    'w-[67%]',
    'w-[68%]',
    'w-[69%]',
    'w-[70%]',
    'w-[71%]',
    'w-[72%]',
    'w-[73%]',
    'w-[74%]',
    'w-[75%]',
    'w-[76%]',
    'w-[77%]',
    'w-[78%]',
    'w-[79%]',
    'w-[80%]',
    'w-[81%]',
    'w-[82%]',
    'w-[83%]',
    'w-[84%]',
    'w-[85%]',
    'w-[86%]',
    'w-[87%]',
    'w-[88%]',
    'w-[89%]',
    'w-[90%]',
    'w-[91%]',
    'w-[92%]',
    'w-[93%]',
    'w-[94%]',
    'w-[95%]',
    'w-[96%]',
    'w-[97%]',
    'w-[98%]',
    'w-[99%]',
    'w-[100%]',
  ],
  plugins: [require('tailwindcss-animate')],
};
